export interface ExerciseDefinition {
  name: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  category: string;
  defaultSets: number;
  defaultReps: number;
  defaultRest: number;
}

export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  // BODYWEIGHT & CALISTHENICS
  { name: "Push-Ups", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Wide Push-Ups", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Archer Push-Ups", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Incline Push-Ups", primaryMuscle: "lower_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Decline Push-Ups", primaryMuscle: "upper_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Explosive Push-Ups", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Dips", primaryMuscle: "lower_chest", secondaryMuscles: ["triceps", "front_delts"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Ring Dips", primaryMuscle: "lower_chest", secondaryMuscles: ["triceps", "front_delts"], equipment: "rings", category: "push", defaultSets: 3, defaultReps: 8, defaultRest: 120 },
  { name: "Pull-Ups", primaryMuscle: "lats", secondaryMuscles: ["biceps", "mid_back", "forearms"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 8, defaultRest: 120 },
  { name: "Chin-Ups", primaryMuscle: "biceps", secondaryMuscles: ["lats", "mid_back", "forearms"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 8, defaultRest: 120 },
  { name: "Archer Pull-Ups", primaryMuscle: "lats", secondaryMuscles: ["biceps", "mid_back"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Commando Pull-Ups", primaryMuscle: "lats", secondaryMuscles: ["biceps", "mid_back", "forearms"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 6, defaultRest: 120 },
  { name: "Muscle-Ups", primaryMuscle: "lats", secondaryMuscles: ["mid_chest", "triceps", "biceps"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 3, defaultRest: 180 },
  { name: "Inverted Rows", primaryMuscle: "mid_back", secondaryMuscles: ["biceps", "rear_delts", "forearms"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Front Lever Progressions", primaryMuscle: "lats", secondaryMuscles: ["abs", "mid_back"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Handstand Push-Ups", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "traps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Pike Push-Ups", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "upper_chest"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Wall Walks", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "abs", "traps"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "L-Sits", primaryMuscle: "abs", secondaryMuscles: ["quads", "obliques", "forearms"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Hanging Leg Raises", primaryMuscle: "abs", secondaryMuscles: ["obliques", "forearms"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Dragon Flags", primaryMuscle: "abs", secondaryMuscles: ["obliques"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 6, defaultRest: 90 },
  { name: "Hollow Holds", primaryMuscle: "abs", secondaryMuscles: ["obliques", "quads"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 30, defaultRest: 60 },
  { name: "Human Flag Progressions", primaryMuscle: "obliques", secondaryMuscles: ["lats", "front_delts"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Pistol Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "calves"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Shrimp Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 6, defaultRest: 120 },
  { name: "Bulgarian Split Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "adductors"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Nordic Hamstring Curls", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "calves"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 5, defaultRest: 120 },
  { name: "Bodyweight Calf Raises", primaryMuscle: "calves", secondaryMuscles: [], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 20, defaultRest: 45 },

  // DUMBBELLS
  { name: "Dumbbell Bench Press", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "dumbbell", category: "push", defaultSets: 4, defaultReps: 10, defaultRest: 90 },
  { name: "Incline Dumbbell Press", primaryMuscle: "upper_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "dumbbell", category: "push", defaultSets: 4, defaultReps: 10, defaultRest: 90 },
  { name: "Dumbbell Flyes", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts"], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Dumbbell Floor Press", primaryMuscle: "mid_chest", secondaryMuscles: ["triceps", "front_delts"], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Dumbbell Pullovers", primaryMuscle: "lats", secondaryMuscles: ["mid_chest", "triceps"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "One-Arm Dumbbell Rows", primaryMuscle: "lats", secondaryMuscles: ["biceps", "mid_back", "rear_delts"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Chest-Supported Dumbbell Rows", primaryMuscle: "mid_back", secondaryMuscles: ["biceps", "rear_delts", "lats"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Renegade Rows", primaryMuscle: "mid_back", secondaryMuscles: ["abs", "biceps", "lats"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Dumbbell Shoulder Press", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "side_delts"], equipment: "dumbbell", category: "push", defaultSets: 4, defaultReps: 10, defaultRest: 90 },
  { name: "Arnold Press", primaryMuscle: "front_delts", secondaryMuscles: ["side_delts", "triceps"], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Front Raises", primaryMuscle: "front_delts", secondaryMuscles: ["side_delts"], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Lateral Raises", primaryMuscle: "side_delts", secondaryMuscles: ["front_delts", "traps"], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Rear-Delt Flyes", primaryMuscle: "rear_delts", secondaryMuscles: ["mid_back", "traps"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Dumbbell Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Hammer Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Concentration Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Triceps Extensions", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Dumbbell Skull Crushers", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "dumbbell", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Goblet Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "adductors"], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 12, defaultRest: 90 },
  { name: "Dumbbell Lunges", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Dumbbell Romanian Deadlifts", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Dumbbell Hip Thrusts", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 12, defaultRest: 90 },
  { name: "Weighted Calf Raises", primaryMuscle: "calves", secondaryMuscles: [], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 45 },

  // BARBELL
  { name: "Bench Press", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "barbell", category: "push", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Incline Bench Press", primaryMuscle: "upper_chest", secondaryMuscles: ["front_delts", "triceps"], equipment: "barbell", category: "push", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Decline Bench Press", primaryMuscle: "lower_chest", secondaryMuscles: ["triceps", "front_delts"], equipment: "barbell", category: "push", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Back Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "lower_back", "adductors"], equipment: "barbell", category: "legs", defaultSets: 4, defaultReps: 8, defaultRest: 150 },
  { name: "Front Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "abs", "upper_chest"], equipment: "barbell", category: "legs", defaultSets: 4, defaultReps: 8, defaultRest: 150 },
  { name: "Deadlifts", primaryMuscle: "lower_back", secondaryMuscles: ["glutes", "hamstrings", "quads", "forearms", "traps"], equipment: "barbell", category: "pull", defaultSets: 4, defaultReps: 5, defaultRest: 180 },
  { name: "Romanian Deadlifts", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "barbell", category: "legs", defaultSets: 4, defaultReps: 10, defaultRest: 120 },
  { name: "Bent-Over Rows", primaryMuscle: "mid_back", secondaryMuscles: ["lats", "biceps", "rear_delts"], equipment: "barbell", category: "pull", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Pendlay Rows", primaryMuscle: "mid_back", secondaryMuscles: ["lats", "biceps", "lower_back"], equipment: "barbell", category: "pull", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Landmine Rows", primaryMuscle: "lats", secondaryMuscles: ["mid_back", "biceps", "rear_delts"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Military Press", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "side_delts", "traps"], equipment: "barbell", category: "push", defaultSets: 4, defaultReps: 8, defaultRest: 120 },
  { name: "Push Press", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "side_delts", "quads"], equipment: "barbell", category: "push", defaultSets: 4, defaultReps: 6, defaultRest: 120 },
  { name: "Barbell Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Skull Crushers", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "barbell", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Hip Thrusts", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "adductors"], equipment: "barbell", category: "legs", defaultSets: 4, defaultReps: 10, defaultRest: 120 },
  { name: "Good Mornings", primaryMuscle: "lower_back", secondaryMuscles: ["hamstrings", "glutes"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Shrugs", primaryMuscle: "traps", secondaryMuscles: ["forearms"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },

  // KETTLEBELLS
  { name: "Kettlebell Swings", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "lower_back", "abs"], equipment: "kettlebell", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Kettlebell Goblet Squats", primaryMuscle: "quads", secondaryMuscles: ["glutes", "adductors"], equipment: "kettlebell", category: "legs", defaultSets: 3, defaultReps: 12, defaultRest: 90 },
  { name: "Clean and Press", primaryMuscle: "front_delts", secondaryMuscles: ["triceps", "traps", "quads"], equipment: "kettlebell", category: "push", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Kettlebell High Pulls", primaryMuscle: "traps", secondaryMuscles: ["rear_delts", "biceps"], equipment: "kettlebell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Kettlebell Romanian Deadlifts", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "kettlebell", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },

  // CABLES
  { name: "Cable Crossovers", primaryMuscle: "mid_chest", secondaryMuscles: ["front_delts"], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Low-to-High Cable Flyes", primaryMuscle: "upper_chest", secondaryMuscles: ["front_delts"], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "High-to-Low Cable Flyes", primaryMuscle: "lower_chest", secondaryMuscles: ["front_delts"], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Lat Pulldowns", primaryMuscle: "lats", secondaryMuscles: ["biceps", "mid_back", "forearms"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Cable Rows", primaryMuscle: "mid_back", secondaryMuscles: ["lats", "biceps", "rear_delts"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Straight-Arm Pulldowns", primaryMuscle: "lats", secondaryMuscles: ["abs", "triceps"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Cable Lateral Raises", primaryMuscle: "side_delts", secondaryMuscles: ["front_delts", "traps"], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Face Pulls", primaryMuscle: "rear_delts", secondaryMuscles: ["mid_back", "traps"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Cable Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Cable Triceps Pushdowns", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },

  // MORE BODYWEIGHT
  { name: "Reverse Curls", primaryMuscle: "forearms", secondaryMuscles: ["biceps"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Farmer's Walks", primaryMuscle: "forearms", secondaryMuscles: ["traps", "abs"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 30, defaultRest: 90 },
  { name: "Woodchops", primaryMuscle: "obliques", secondaryMuscles: ["abs"], equipment: "cable", category: "core", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Russian Twists", primaryMuscle: "obliques", secondaryMuscles: ["abs"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 20, defaultRest: 60 },
  { name: "Side Planks", primaryMuscle: "obliques", secondaryMuscles: ["abs", "glutes"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 30, defaultRest: 60 },
  { name: "Sumo Squats", primaryMuscle: "adductors", secondaryMuscles: ["quads", "glutes"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Copenhagen Planks", primaryMuscle: "adductors", secondaryMuscles: ["obliques", "abs"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Cable Hip Adduction", primaryMuscle: "adductors", secondaryMuscles: [], equipment: "cable", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Standing Calf Raises", primaryMuscle: "calves", secondaryMuscles: [], equipment: "machine", category: "legs", defaultSets: 4, defaultReps: 15, defaultRest: 45 },
  { name: "Seated Calf Raises", primaryMuscle: "calves", secondaryMuscles: [], equipment: "machine", category: "legs", defaultSets: 4, defaultReps: 15, defaultRest: 45 },
  { name: "Back Extensions", primaryMuscle: "lower_back", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "pull", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Rack Pulls", primaryMuscle: "traps", secondaryMuscles: ["lower_back", "forearms", "glutes"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 6, defaultRest: 120 },
  { name: "Reverse Cable Flyes", primaryMuscle: "rear_delts", secondaryMuscles: ["mid_back", "traps"], equipment: "cable", category: "pull", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Leg Press", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "machine", category: "legs", defaultSets: 4, defaultReps: 10, defaultRest: 120 },
  { name: "Leg Curls", primaryMuscle: "hamstrings", secondaryMuscles: ["calves"], equipment: "machine", category: "legs", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Sumo Deadlifts", primaryMuscle: "glutes", secondaryMuscles: ["quads", "hamstrings", "adductors", "lower_back"], equipment: "barbell", category: "legs", defaultSets: 4, defaultReps: 6, defaultRest: 150 },
  { name: "Reverse Lunges", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Step-Ups", primaryMuscle: "quads", secondaryMuscles: ["glutes", "calves"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Plank", primaryMuscle: "abs", secondaryMuscles: ["obliques"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 60, defaultRest: 60 },
  { name: "Ab Wheel Rollouts", primaryMuscle: "abs", secondaryMuscles: ["obliques", "lats"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Cable Crunches", primaryMuscle: "abs", secondaryMuscles: ["obliques"], equipment: "cable", category: "core", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Bicycle Crunches", primaryMuscle: "obliques", secondaryMuscles: ["abs"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 20, defaultRest: 60 },
  { name: "Mountain Climbers", primaryMuscle: "abs", secondaryMuscles: ["obliques", "quads", "front_delts"], equipment: "bodyweight", category: "core", defaultSets: 3, defaultReps: 20, defaultRest: 60 },
  { name: "Pallof Press", primaryMuscle: "obliques", secondaryMuscles: ["abs"], equipment: "cable", category: "core", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Overhead Triceps Extension", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "cable", category: "push", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Diamond Push-Ups", primaryMuscle: "triceps", secondaryMuscles: ["mid_chest", "front_delts"], equipment: "bodyweight", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Preacher Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Incline Dumbbell Curls", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Wrist Curls", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 15, defaultRest: 45 },
  { name: "T-Bar Rows", primaryMuscle: "mid_back", secondaryMuscles: ["lats", "biceps", "rear_delts"], equipment: "barbell", category: "pull", defaultSets: 4, defaultReps: 10, defaultRest: 90 },
  { name: "Dumbbell Shrugs", primaryMuscle: "traps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Upright Rows", primaryMuscle: "traps", secondaryMuscles: ["side_delts", "front_delts"], equipment: "barbell", category: "pull", defaultSets: 3, defaultReps: 10, defaultRest: 60 },
  { name: "Close-Grip Bench Press", primaryMuscle: "triceps", secondaryMuscles: ["mid_chest", "front_delts"], equipment: "barbell", category: "push", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Glute Bridges", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 60 },
  { name: "Box Jumps", primaryMuscle: "quads", secondaryMuscles: ["glutes", "calves", "hamstrings"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Walking Lunges", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 12, defaultRest: 60 },
  { name: "Single-Leg Romanian Deadlifts", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "dumbbell", category: "legs", defaultSets: 3, defaultReps: 10, defaultRest: 90 },
  { name: "Glute-Ham Raises", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Cossack Squats", primaryMuscle: "adductors", secondaryMuscles: ["quads", "glutes"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 8, defaultRest: 90 },
  { name: "Donkey Calf Raises", primaryMuscle: "calves", secondaryMuscles: [], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 15, defaultRest: 45 },
  { name: "Jump Rope", primaryMuscle: "calves", secondaryMuscles: ["quads", "forearms"], equipment: "bodyweight", category: "legs", defaultSets: 3, defaultReps: 60, defaultRest: 60 },
];

export const EXERCISE_MAP = Object.fromEntries(EXERCISE_LIBRARY.map((e) => [e.name, e]));
